AWSTemplateFormatVersion: 2010-09-09
Transform:
- AWS::Serverless-2016-10-31
- AWS::CodeStar

Parameters:
  ProjectId:
    Type: String
    Description: AWS Lambda Function THat wraps TAXJAT tax calculation

Resources:
  USTaxCalculation:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs4.3
      Environment:
              Variables:
                TAXJAR_API_KEY: TAXJAR_API_KEY
                WAREHOUSE_COUNTRY: WAREHOUSE_COUNTRY
                WAREHOUSE_POSTAL_CODE: WAREHOUSE_POSTAL_CODE
                WAREHOUSE_STATE: WAREHOUSE_STATE
      Role:
        Fn::ImportValue:
          !Join ['-', [!Ref 'ProjectId', !Ref 'AWS::Region', 'LambdaTrustRole']]

